name: CI
on:
  push:
    branches:
    - master
    tags:
    - "v*"
  pull_request:

jobs:

  update-website:
    name: Update website
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: coursier/cache-action@v6.3
      - uses: coursier/setup-action@v1
        with:
          jvm: 8
      - run: npm install && export PATH="$PATH:$(pwd)/node_modules/bower/bin" && ./mill -i updateWebsite
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
